name: jotrockenmitlockenrepo
description: "Central modular code for my flutter/dart projects."
version: 1.1.0
homepage: https://jonasheinle.de

environment:
  sdk: ">=3.10.1 <4.0.0"
  flutter: ">=3.38.3"

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  url_launcher: ^6.3.2
  go_router: ^17.0.0
  markdown: ^7.3.0
  markdown_widget: ^2.3.2+8
  flutter_highlighter: ^0.1.1
  font_awesome_flutter: ^10.12.0
  fl_chart: ^1.1.1
  mime: ^2.0.0
  web: ^1.1.1

  flutter_markdown: any
dev_dependencies:
  mockito: ^5.5.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
